### ISSUE TITLE
readme says "bundleInfo.getIcon" update it to "bundleInfo.getIconFile"

### ISSUE THREAD

**Issue by aishwat** [jakubknejzlik/app-bundle-info#1]
title says it

**Comment by aishwat** [comment]
tried for apk it says "Error: no file found for '*_/drawable-_/ic_launcher.png'" whereas on decompressing apk and i can see icon is there? any idea 
_btw great module, thanks man :)_

**Comment by jakubknejzlik** [comment]
Good point :) . Can't really say where's the problem with ic_launcher without the apk file. Could you send it to me without any other files (just with the icon)?

**Comment by aishwat** [comment]
ya here's the apk https://drive.google.com/file/d/0B7tONtP3zP1BTDcyNnBES2k3dm8/view?usp=sharing

**Comment by jakubknejzlik** [comment]
Ok, now I see the problem. The module expects that the icon is named ic_launcher.png (I've been told, that it's the default name for this icon, but it can be changed). I tried to parse you manifest.xml (to get the icon path from it), but unfortunately it doesn't show the icon path. Is it possible for you to use ic_launcher.png as icon name?

**Comment by aishwat** [comment]
ya u r right, my bad , closing issue 
thanks man :)
