### ISSUE TITLE
I got 'Uncaught TypeError: Cannot read property 'prototype' of undefined' when I import 'app-bundle-info'

### ISSUE THREAD

**Issue by JimmyDaddy** [jakubknejzlik/app-bundle-info#4]
![_001](https://cloud.githubusercontent.com/assets/16460813/18057992/e8d8fa76-6e44-11e6-9406-56ccd31028d5.png)

**Comment by jakubknejzlik** [comment]
@CJHJim thanks for report! Could you be more specific about environment (what version of nodejs) and stack trace?

**Comment by JimmyDaddy** [comment]
@jakubknejzlik my nodejs version is 5.3.0,

**Comment by JimmyDaddy** [comment]
This problem appeared in Ubuntu16.10,
and it also happen in MacOsx  
![hot update service google chrome at 10 20 45](https://cloud.githubusercontent.com/assets/16460813/18073624/2477352a-6e9a-11e6-874a-860d0aea248c.png)
![hot update service google chrome at 10 21 30](https://cloud.githubusercontent.com/assets/16460813/18073636/38f88b5c-6e9a-11e6-8721-7b2213d1ed69.png)

I think this is the same as the problem appeared in Ubuntu16.10, nodejs version is 5.3.0

**Comment by jakubknejzlik** [comment]
Thanks @CJHJim, but unfortunately I don't see how this is related to `app-bundle-info` module.
