### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by tspoke** [jakubknejzlik/app-bundle-info#6]
Hi,

I use a lot your package and I noticed that it is very large because you include the test folder which contains tests APK and IPA. I think it could be better if you exclude them :)

http://stackoverflow.com/questions/8617753/exclude-test-code-in-npm-package

Thank you, have a nice day

**Comment by jakubknejzlik** [comment]
@tspoke good idea, thanks for pointing that out 👍  ... I've added .npmignore file to exclude test folder completely
